### ISSUE TITLE
Requires plugins doesn't seem to work

### ISSUE THREAD

**Issue by justinkruit** [WordPress/plugin-check-action#174]
https://github.com/WordPress/plugin-check-action/blob/862fefb6dd127a406f57e6ee5f55b7c6564b626d/action.yml#L95

Hi, it doesn't seem that the requires plugin field is actually getting any info, resulting in a failed test. My plugin adds a woocommerce shipping method which requires the use of a class by WC which can't be found by the test. Is there a way to fix this? It's the first time I'm testing with GitHub actions and would love to have this set up 😁

**Comment by swissspidy** [comment]
Please share your GitHub repository and how you define your plugin dependencies.

**Comment by justinkruit** [comment]
@swissspidy I've given you access to the private repo.

**Comment by swissspidy** [comment]
Awesome, thanks.

So the WooCommerce dependency is definitely seen as it is correctly installed:

```
Installing WooCommerce (9.3.2)
Downloading installation package from https://downloads.wordpress.org/plugin/woocommerce.9.3.2.zip...
Unpacking the package...
Installing the plugin...
Plugin installed successfully.
Activating 'woocommerce'...
Plugin 'woocommerce' activated.
Success: Installed 1 of 1 plugins.
```

P.S. The output is a bit cluttered because your plugin is registering scripts too early. Your `registerScripts()` method is fired on `plugins_loaded` but the earliest you can do it is `init`. To fix this, you could do:

```diff
-$this->registerScripts();
-$this->registerStyles();
+add_action('init', [$this, 'registerScripts']);
+add_action('init', [$this, 'registerStyles']);
```

Further, you are calling `$this->autoRequireDir('includes');` on `plugins_loaded` too, which means your `ShippingMethod` class is loaded at that point.

According to the [WooCommerce documentation](https://github.com/woocommerce/woocommerce/blob/bca89cb14fa7f52c8d04680b73661d57deea5f07/docs/shipping/shipping-method-api.md#create-a-function-to-house-your-class), that is too early, as custom shipping classes should only be loaded at the `woocommerce_shipping_init` hook.

So the issue is not with Plugin Check but with how you are trying to access this WooCommerce class too early. Their documentation looks helpful so I'd start there with debugging :-)

Good luck!

**Comment by justinkruit** [comment]
Thank you very much! Especially for the long and helpful response. Made some changes, and now it does seem to be working. Time to fix some stuff it outputted ;-)

I was wondering however why requires_plugins isn't a valid field when I try it in the terminal, while the same command seems to work in the script:
```
boelens-graszoden\app\public>wp plugin get boelens-graszoden --field=requires_plugins
Error: Invalid field: requires_plugins.
```

**Comment by swissspidy** [comment]
You are probably running an outdated version of WP-CLI or `wp-cli/extension-command`.

The latest version is WP-CLI v2.11.0
